model:
  model_name: "unsloth/gemma-3-1b-it"
  output_dir: "results"
  max_length: 512
  packing: false
  num_train_epochs: 5
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4          
  gradient_checkpointing: false
  optim: "adamw_8bit"
  warmup_steps: 5                          
  logging_steps: 1
  save_strategy: "epoch"
  eval_strategy: "epoch"
  learning_rate: 5e-5
  weight_decay: 0.01                       
  lr_scheduler_type: "constant"
  seed: 3407                               
  report_to: "none"                        
  dataset_text_field: "text"
  load_in_8bit: false
  load_in_4bit: false
  max_steps: 30                             


  peft_config:
    r: 8
    lora_alpha: 32
    lora_dropout: 0.05
    bias: null
    random_state: 42
    use_rslora: false
    finetune_mlp_modules: true
    target_modules: 
      - "gate_proj"
      - "up_proj"
      - "down_proj"

dataset:
  train_path: ''
  valid_path: ''
  test_path: ''

hyperparameter_search:
  enable: false
  n_trials: 6
  hyperparameter_space:


